add kitchen ci and travis support [WIP]
salt-formulas/salt-formula-git pull request #1
Opened 2017-01-11 09:47 UTC by epcim

Add kitchen CI.
Add travis builds.

Uses features from https://github.com/simonmcc/kitchen-salt/pull/78 (in other words it allow resolve and install multiple formula dependencies from git/spm/apt/yum.

Ready for comments. It's WIP but fully works.

This formula is being used for kitchen-salt build verification.

2017-01-11 09:47 UTC, epcim commented
Makefile for testkitchen may be uploaded, but I would avoid place it on pipeline this time.

2017-01-11 09:50 UTC, epcim commented on .kitchen.yml
> +    # Test of git external dependencies that are not directly required
This two not required formulas will be removed.

2017-01-11 10:42 UTC, fpytloun commented on .travis.yml
> +    - docker
Only two spaces for yaml

2017-01-11 10:42 UTC, fpytloun commented on Makefile
> +	#@echo "make kitchen - Run Kitchen CI tests (create, converge, verify)"
Uncomment this?

2017-01-11 10:46 UTC, fpytloun commented on .kitchen.yml
> +      source: https://github.com/tcpcloud/salt-formula-nginx.git
I would wait when we'll know final location of salt-formulas before doing tests for all of them. I would use git repository for deploying dependencies (or have some env-variable to decide?)

Also this is interesting (just FYI): https://docs.travis-ci.com/user/deployment/launchpad/
And we'll probably do that to have package builds.

2017-01-11 14:02 UTC, epcim commented on Makefile
> +	#@echo "make kitchen - Run Kitchen CI tests (create, converge, verify)"
Will it break tests if proper environment not exist on jenkins slaves?

2017-01-27 15:24 UTC, fpytloun commented
It would be good to have possibility to install kitchen without root and messing up the system.
I was thinking about following:
```
bundle install --path `pwd`/.vendor/bundle
```
to install kitchen and deps into formula's directory (and add .vendor into .gitignore).

Unfortunately I am failing with following error on Debian Stretch:
```
$ bundle install --path `pwd`/.vendor/bundle                                                                                                                                                                                                                                                                    (add-travis) 
Fetching https://github.com/epcim/kitchen-salt.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Installing public_suffix 2.0.5
Installing artifactory 2.5.1
Installing builder 3.2.3
Installing coderay 1.1.1
Installing diff-lcs 1.3
Installing excon 0.54.0
Installing json 2.0.3 with native extensions
Installing unf_ext 0.0.7.2 with native extensions
Installing erubis 2.7.0
Installing ffi 1.9.17 with native extensions
Installing hashie 3.4.6
Installing http-form_data 1.0.1
Installing http_parser.rb 0.6.0 with native extensions
Installing httpclient 2.8.3
Installing method_source 0.8.2
Installing mixlib-log 1.7.1
Installing parallel 1.10.0
Installing slop 3.6.0
Installing rainbow 2.2.1 with native extensions
Installing rspec-support 3.5.0
Installing rubyzip 1.2.0
Installing sslshake 1.0.13
Installing thor 0.19.4
Installing mixlib-shellout 2.2.7
Installing net-ssh 4.0.1
Installing little-plugger 1.1.4
Installing multi_json 1.12.1
Installing nori 2.6.0
Installing rubyntlm 0.6.1
Installing mixlib-versioning 1.1.0
Installing safe_yaml 1.0.4
Using bundler 1.13.6
Installing addressable 2.5.0
Installing gyoku 1.3.1
Installing docker-api 1.33.2
Installing unf 0.1.4
Installing gssapi 1.2.0
Installing pry 0.10.4
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/filip/src/tcpcloud/salt-formulas/salt-formulas/git/.vendor/bundle/ruby/2.3.0/gems/rainbow-2.2.1/ext
/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /home/filip/src/tcpcloud/salt-formulas/salt-formulas/git/.vendor/bundle/ruby/2.3.0/gems/rainbow-2.2.1/ext
rake2.3 RUBYARCHDIR=/home/filip/src/tcpcloud/salt-formulas/salt-formulas/git/.vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1
RUBYLIBDIR=/home/filip/src/tcpcloud/salt-formulas/salt-formulas/git/.vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1
sh: 1: rake2.3: not found

rake failed, exit code 127

Gem files will remain installed in /home/filip/src/tcpcloud/salt-formulas/salt-formulas/git/.vendor/bundle/ruby/2.3.0/gems/rainbow-2.2.1 for inspection.
Results logged to /home/filip/src/tcpcloud/salt-formulas/salt-formulas/git/.vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1/gem_make.out

An error occurred while installing rainbow (2.2.1), and Bundler cannot continue.
Make sure that `gem install rainbow -v '2.2.1'` succeeds before bundling.
```

2017-01-27 15:31 UTC, fpytloun commented
This fixed the installation issue for me:
```ln -s /usr/bin/rake /usr/bin/rake2.3```
Still needs to add `.vendor/bundle/ruby/2.3.0/bin/kitchen` into PATH.

2017-01-30 08:49 UTC, epcim commented
[**@fpytloun**](https://github.com/fpytloun) commented on [Jan 27, 2017, 4:31 PM GMT+1](https://github.com/salt-formulas/salt-formula-git/pull/1#issuecomment-275692540 "2017-01-27T15:31:03Z - Replied by Github Reply Comments"):
> This fixed the installation issue for me:
> ```ln -s /usr/bin/rake /usr/bin/rake2.3```
> 
> But then I got the same issue as once had:
> ```
> $ bundle exec kitchen test
> -----> Starting Kitchen (v1.15.0)
> >>>>>> ------Exception-------
> >>>>>> Class: Kitchen::UserError
> >>>>>> Message: You must first install the Docker CLI tool http://www.docker.io/gettingstarted/
> >>>>>> ----------------------
> >>>>>> Please see .kitchen/logs/kitchen.log for more details
> >>>>>> Also try running `kitchen diagnose --all` for configuration
> ```

Zalezi jaky driver: se specifikuje v pouzitem .kitchen*.yml. by default docker -> docker cli musi byt dostupne na path. (bundle exec ti mozna upravi env). V Travisu je to je v pohode. Zkusim u sebe.

2017-01-30 09:02 UTC, epcim commented
[**@fpytloun**](https://github.com/fpytloun) commented on [Jan 27, 2017, 4:24 PM GMT+1](https://github.com/salt-formulas/salt-formula-git/pull/1#issuecomment-275690934 "2017-01-27T15:24:51Z - Replied by Github Reply Comments"):
> It would be good to have possibility to install kitchen without root and messing up the system.
> I was thinking about following:
> ```
> bundle install --path `pwd`/.vendor/bundle
> ```

Common dev setup is user side ruby using one of the ruby managers (same as if you have python-virtualenv). I quite believe that bundle installs user side by default ( http://bundler.io/v1.3/man/bundle-install.1.html see --system).

Kitchen .yml has use sudo set as there is an requirement for travis (not sure which one now, but will review) . It's supposed to work without it locally - for that reason alternative .kitchen.yml may be provided.

2017-01-30 12:24 UTC, cznewt requested changes

2017-01-30 12:24 UTC, cznewt commented on INTEGRATION.rst
> +
to documentation

2017-01-30 12:24 UTC, cznewt commented on README.rst
> +Development and test workflow with `Test Kitchen <http://kitchen.ci>`_ and
Links to documentation

2017-01-30 13:00 UTC, fpytloun commented on .kitchen.yml
> +  vendor_repo:
I would remove setup of APT repository as it's not going to be used (at least before we have custom PPA).
Also remove useless comments.

2017-01-30 13:00 UTC, fpytloun commented on .kitchen.yml
> +
Unwanted empty line

2017-01-30 13:01 UTC, fpytloun commented on INTEGRATION.rst
> +
+1, mention something shorter about testing in readme and more important describe testing in documentation in salt-formulas repo.
We don't want to duplicate the same long text in each repo.

2017-02-09 07:39 UTC, fpytloun commented on .kitchen.yml
> +  vendor_repo:
This should not be used.

2017-02-09 07:40 UTC, fpytloun commented on Gemfile
> +source 'https://rubygems.org'
Remove gemfile

2017-02-09 14:38 UTC, fpytloun commented on .kitchen.yml
> +  use_sudo: true
Can we set this to false? Otherwise kitchen is not able to detect docker binary.

2017-02-10 11:08 UTC, merged